<cfscript>
// this file is generated by jenkins and sets these variables to build environment values
set(environment = "development"); // [development|production]
set(stage = "dev"); // [dev|ci|staging|prod]
</cfscript>
